name: Deploy Users Service
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install
      - name: Test
        run: |
          npm run test:coverage
  deploy:
    needs:
      - test
    name: Deploy
    uses: ./.github/workflows/deploy-frontend-workflow.yaml
    with:
      service: 'frontend'
      region: 'us-central1'
      source: '.'
    secrets:
      wif_provider: ${{ secrets.WIF_PROVIDER }}
      wif_service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}